name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "prod" ]  # Deploy when prod branch updates

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm ci

    - name: Build Angular App
      run: npm run build -- --output-path=dist/angular-github-actions --base-href="/angular-github-actions/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true
