name: Sync main to prod and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger when main is updated

jobs:
  sync-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all branches

    - name: Ensure prod branch exists and sync with main
      run: |
        git fetch origin prod || echo "prod branch does not exist yet"
        git checkout prod || git checkout -b prod
        git reset --hard origin/main  # Force sync prod with main
        git push --force origin prod  # Force push to avoid conflicts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: sync-prod  # Wait until the prod branch is updated
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: prod  # Build using the latest prod branch

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm ci

    - name: Build Production Version
      run: npm run build -- --configuration=production --output-path=dist --base-href="/angular-github-actions/"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Ensure deployment happens on gh-pages
        folder: dist  # The build folder that needs to be deployed
        clean: true
